package br.com.DynamoDB.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "funcionario")
public class Funcionario {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String funcionarioId;

    @DynamoDBAttribute
    private String nome;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private Departamento departamento;

}
